# deploy.yml

name: Deploy React App to GitHub Pages

on:
  # Roda quando um push é feito para a branch `main`
  push:
    branches: ["main"]

  # Permite que você rode este workflow manualmente pela aba Actions do GitHub
  workflow_dispatch:

# Permissões para a Action poder fazer o deploy
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Job único de build e deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Use uma versão recente do Node.js
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        # Adicione o comando base aqui também, conforme configurado no vite.config.ts
        run: npm run build -- --base=./ 
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pasta onde o build foi gerado (o padrão do Vite é 'dist')
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
